import Header from "./components/header/Header";
import Sidebar from "./components/sidebar/Sidebar";
import SidebarRight from "./components/sidebar_right/SidebarRight";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-[92rem] mx-auto">
        <Header />
        <div className="md:grid md:grid-cols-12">
          <div className="md:col-span-3 lg:col-span-2 hidden md:block border-r border-gray-200 shadow-xl">
            <Sidebar />
          </div>
          <div className="md:col-span-7">{children}</div>
          <div className="md:col-span-2 lg:col-span-3 hidden md:block border-l border-gray-200 shadow-xl">
            <SidebarRight />
          </div>
        </div>
      </body>
    </html>
  );
}
